# Generated by script/gen-formula for each release; do not edit by hand.
class Yass < Formula
  desc "Read-only CLI serving yass spec sets to coding agents"
  homepage "https://github.com/shakefu/yass"
  version "0.2.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shakefu/yass/releases/download/v0.2.0/yass_0.2.0_darwin_arm64.tar.gz"
      sha256 "ba779b3b51548e92a8581c479827c7edd00d1a26f3b9333f3860b65bc726f3a0"
    else
      url "https://github.com/shakefu/yass/releases/download/v0.2.0/yass_0.2.0_darwin_amd64.tar.gz"
      sha256 "f097aaf8698a8e1140343a20086e4ff57561d815718e5ddc99cdd788e60b05d1"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/shakefu/yass/releases/download/v0.2.0/yass_0.2.0_linux_arm64.tar.gz"
      sha256 "be78627a06bae3b294a35b1573a5fd4eec17d9ea18fda8eb5057e63c299a0cab"
    else
      url "https://github.com/shakefu/yass/releases/download/v0.2.0/yass_0.2.0_linux_amd64.tar.gz"
      sha256 "2c95bbb967983c6f20adc19b4eddf97aa4df9ce161c25edafc3312e32bae731e"
    end
  end

  def install
    bin.install "yass"
  end

  test do
    assert_match "yass 0.2.0", shell_output("#{bin}/yass --version")
  end
end
