# Generated by script/gen-formula for each release; do not edit by hand.
class Yass < Formula
  desc "Read-only CLI serving yass spec sets to coding agents"
  homepage "https://github.com/shakefu/yass"
  version "0.4.2"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shakefu/yass/releases/download/v0.4.2/yass_0.4.2_darwin_arm64.tar.gz"
      sha256 "87501809a34e51345c1f102f64efe37385575518b83f09a1b4b29e40f7798e7a"
    else
      url "https://github.com/shakefu/yass/releases/download/v0.4.2/yass_0.4.2_darwin_amd64.tar.gz"
      sha256 "596c561b6814cf76c13b3bcda1ebb9bd8965a8eb949646edcbbb03f47c85561b"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/shakefu/yass/releases/download/v0.4.2/yass_0.4.2_linux_arm64.tar.gz"
      sha256 "71975f3f93cd4605c5ed76249732bade3c8fef13ac910cade36e31915510d62b"
    else
      url "https://github.com/shakefu/yass/releases/download/v0.4.2/yass_0.4.2_linux_amd64.tar.gz"
      sha256 "0fce231337b3ec790d8c785f072068a84b267c2e047dec67f6c2a2a73ab4c03a"
    end
  end

  def install
    bin.install "yass"
  end

  test do
    assert_match "yass 0.4.2", shell_output("#{bin}/yass --version")
  end
end
